### ISSUE TITLE
RoPot reporting luminance - but doesn't have this capcability

### ISSUE THREAD

**Issue by cbho** [koktaildotcom/homey-mi-flora#5] opened 2018-04-11 15:15 UTC
The RoPot (unfortunately) does not have the capability to measure the surrounding light - so reporting this capability is not relevant.

**Comment by koktaildotcom** [comment] 2018-04-11 18:46
Thanks for reporting. I'll disable this capability for the RoPot.

**Comment by koktaildotcom** [comment] 2018-04-17 15:34
The issue is resolved in v1.0.2

**Closed** 2018-04-17 15:33 UTC
Labels: bug
